# Generated by Django 4.0.4 on 2022-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_members_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='car_number',
            field=models.CharField(default='abc12', max_length=15, unique=True),
        ),
    ]
